OS ?= FreeBSD
#OS ?= NetBSD
#OS ?= OpenBSD

CFLAGS ?= -O2 -Wall
CC ?= gcc

.if $(OS) == "FreeBSD"
CFLAGS += -DUSE_LIBUSB
LIBS =  -lusb
.elif $(OS) == "NetBSD" || $(OS) == "OpenBSD"
CFLAGS += -DUSE_UHID
LIBS =
.endif


hid_bootloader_cli_unix: hid_bootloader_cli_unix.c
	$(CC) $(CFLAGS) -s -o hid_bootloader_cli_unix hid_bootloader_cli_unix.c $(LIBS)

clean:
	rm -f hid_bootloader_cli_unix
